title: Viridian Sky
description: Soft whispers spoken to me in my daydreams.
  Stories like little fragments of my heart and soul.
author: Skylar Viridian
header-image: /img/green-sky.jpg
nickname: Skylar
author-nick: Skylar Viridian
bio: I'm an author and I love writing. Stories that resonate with my very being
  or poems like echoes from my soul. Pen is my tool, my weapon. It is the key to my heart.
email: viridiansky@protonmail.com
baseurl: ""
url: "https://viridiansky.net"
twitter_username: ViridianSkylar
github_username:  skylarvi
header-img: green-sky.jpg

# Plugins
    
plugins:
  - github-pages
  - jekyll-email-protect
  - jekyll-paginate
  - jekyll-webmention_io
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO config

logo: /img/avatar.png
twitter:
  username: ViridianSkylar
  card: summary
social:
  name: Skylar Viridian
  links:
    - https://twitter.com/SkylarViridian
    - https://github.com/skylarvi
webmaster_verifications:
  google: CHANGEME

# Build settings
include: ['_pages']
markdown: kramdown

# paginate
paginate: 5

#webmentions
webmentions:
  username: viridiansky.net
  cache_folder: .cache

social-bar:
  services:
    - service: twitter
      username: ViridianSkylar
      href: https://twitter.com/ViridianSkylar
    - service: github
      username: skylarvi
      href: https://github.com/skylarvi

navigation:
  links:
    - title: home
      href: index.html
    - title: about
      href: #

repository: "skylarvi/viridiansky.net"
staticman:
  branch: "master"